### ISSUE TITLE
[12.0] Migrate cooperators data from another ERP.

### ISSUE THREAD

**Issue by danypr92** [coopiteasy/vertical-cooperative#138]
Hi,

We are working on Partner data migration from another ERP to Odoo, using the EMC modules to manage the memberships.

When we are importing the partner data, we can't import the `effective_date` because it is a computed field that depends on `share_ids`.

Can we create partners with `effective_date` without creating `share_lines`?
Do you have experience in this kind of data migration with membership data?

Thanks!

**Comment by enricostano** [comment]
@danypr92 remember mentioning @robinkeunen or @houssine78 if you want them to get a notification.

**Comment by houssine78** [comment]
Hi @danypr92 in fact for importing data to odoo from external data. We do it sticking to the EMC workflow.

It means that instead of importing directectly data in res_partner. You import the data in the subscription request.

So the steps should be : 
- import the subscription request
- deactivate the ongoing mail server in Odoo
- validate the subscription request
- import the bank statement for all the share payment
- reconcile the payment with the capital release request (cooperator invoice)
- important : reconcilation has to be done in the order of the payment (this is for having the right cooperator number and share register)
- note that only full share payment convert a cooperator candidate to cooperator
- reactivate ongoing mail server (delete all the mail in failing state related to the cooperator import process)

I hope it's clear :)

for more info on the process you should take contact with Catherine or Virginie they are the import mistresses ;)

**Comment by danypr92** [comment]
Thanks @houssine78!

We ended up creating a script with ERPPeek:

https://gitlab.com/coopdevs/migration-tryton-odoo-somconnexio-scripts/-/blob/master/erppeek/erppeek-script.py

**Comment by houssine78** [comment]
you're welcome @danypr92 @enricostano 

I see that you bypass the standard workflow. In your script, you create share line for the cooperator with a quantity of one. So I suppose that each cooperator has only one share.

Your script doesn't seem to create a subscription register (this is different to the subscription request). The subscription register is the share register of the cooperative. It's important to have the subscription register correctly set cause this is this give the share lifecycle history of the cooperative. This is also the element on which the dividend module base it's calculation (same goes for tax reduction certificate in Belgium)

**Comment by enricostano** [comment]
> I see that you bypass the standard workflow. In your script, you create share line for the cooperator with a quantity of one. So I suppose that each cooperator has only one share.

Exactly, in the majority of cases in Spain you can only own 1 share of cooperative capital.

> Your script doesn't seem to create a subscription register (this is different to the subscription request). The subscription register is the share register of the cooperative. It's important to have the subscription register correctly set cause this is this give the share lifecycle history of the cooperative. This is also the element on which the dividend module base it's calculation (same goes for tax reduction certificate in Belgium)

We're aware, more or less :sweat_smile: . In this specific case we hope it will not create issues in the future. But in any case we should update the script taking in account subscription register :+1:
