### ISSUE TITLE
Loan issues

### ISSUE THREAD

**Issue by Patrickkappert** [coopiteasy/vertical-cooperative#143]
When you open a loan issue and someone inscribes you validate and then you pass it over to Paid. But there is no "register payment wizard" to register the money entrance at the bank and the account of the financial balance where it has to be apointed. We have to make the accounting entry by hand?

**Comment by robinkeunen** [comment]
@Patrickkappert Yes, we did not link the payments into that module so far. We made a makeshift system [here](https://github.com/coopiteasy/vertical-cooperative/pull/144) (@vvrossem ) as our customer does not use accounting.

Maybe @houssine78 will have more to say?

**Comment by houssine78** [comment]
Hi @Patrickkappert we are on the making of improvements of the loan module which will integrate the accounting for loan.

that improvement will allows you to register the payment through the standard bank statement reconciliation. once you activate the accounting on loan mngt https://github.com/coopiteasy/vertical-cooperative/pull/134

This PR brings improvements on easy_my_coop_loan and add two modules easy_my_coop_loan_bba (for structured communication for payment) and easy_my_coop_loan_account for all the accounting entries ties to loan.

easy_my_coop_loan_account module generate the account move lines that allow you to use the bank statement reconciliation process. If you don't plan to use accounting there is a paid button coming with the new module of easy_my_coop_loan that will allows you to mark a loan as paid (in the sens that the loaner sent you the money).

Please be aware that this branch still in WIP and still needs to be tested properly. That branch may receive some modification or refactoring that could break the actual data model of the branch (not the main branch). So I strongly advise to not use the PR in production while not merged on 12.0 branch.

I hope it makes it clearer for you. Otherwise don't hesitate to come back to me (end of year is really busy so an answer make take some time).

**Comment by Patrickkappert** [comment]
I have a test server so I could try and get back with observations.. Where is the code available as a download? Some repository?

**Comment by houssine78** [comment]
@Patrickkappert the code is [here](https://github.com/coopiteasy/vertical-cooperative/tree/12.0-loan-improvements). But I still need to rebase on the 12.0 branch. It'll be probably done by Wednesday.
