### ISSUE TITLE
Integrate rename_deprecated_module.py into the migration scripts

### ISSUE THREAD

**Issue by robinkeunen** [coopiteasy/vertical-cooperative#233]

**Comment by victor-champonnois** [comment]
Also I added some migrations queries in the fix_dbs.sh script, maybe I should put it in the "rename_deprecated_module.py" ?

**Comment by robinkeunen** [comment]
@victor-champonnois I rather think you should put the query in the `pre-migration.py` file of `cooperator_website`.

**Comment by victor-champonnois** [comment]
OK :+1:

**Comment by victor-champonnois** [comment]
@huguesdk Tu sais ce qu'il en est de cette tâche ? Je sais pas trop en quoi ça consiste...

**Comment by huguesdk** [comment]
i remember pleading in favor of using migration scripts in the deprecated modules to handle the whole modules and data migration : renaming data tables and renaming modules, or installing the new ones and uninstalling themselves, and the new ones could handle the data renaming in their own migration scripts. i think the latter is more where we’re going, isn’t it? the general idea is to be able to have a seamless transition, with no script to run manually. just updating modules should do.

i am supposed to make some tests about this (but did not start yet). is it still needed?

**Comment by victor-champonnois** [comment]
ok, The situation now is:
- the renaming of modules is done with a [separate script](https://github.com/coopiteasy/vertical-cooperative/blob/12.0-komunigi/rename_deprecated_modules.py)
- the data migration is done with in-modules migration scripts.

It would take quite some time to put all the renaming into in-modules migration scripts. I am not sure it is worth it, since it should only be run once. But I will not be the one who actually does the migration in prod ^^. Tell me what you think :)

Note : it will be different for obeesdoo, I try to include all the migration in the modules themselves.

**Comment by victor-champonnois** [comment]
@huguesdk up sur cette question :)

**Comment by huguesdk** [comment]
i don’t know whether it would be worth it or not for this use case. what would be nice to have, at least, is an easy way to rename an installed module by either updating it or installing the new one, because it could be useful in the future for other modules. maybe a way is already documented somewhere?

i see that the script is quite simple. at least a test with one module (using `openupgrade.update_module_names()`) would be worth doing.

**Comment by victor-champonnois** [comment]
@huguesdk @carmenbianca 
I made a few tests :
What is working now is the following:
Keep a minimal "easy_my_coop" module with only a manifest a pre-migration script. This script: 
- rename the xml_ids (by also changing the module name, ex : easy_my_coop.id -> cooperator.id) Note : this script is copy pasted from the cooperator pre-migration, only changing the module names to easy_my_coop. 
- delete the records from which xml_ids were not renamed (I could also have renamed them, I think it is the same)
- install cooperator (with button.install() )

The cooperator module no longer has a pre-migration script, but has a post_init_hook (running after installation) that uninstall easy_my_coop.

I made a PR just so you can see the code : https://github.com/coopiteasy/vertical-cooperative/pull/326

What's good in this solution : 
- it works :smile: 

What's bad:
- need to keep the easy_my_coop module in the repo
- need a bit of work : for each modules, ensure that all records (views,action...) are either renamed or deleted in easy_my_coop.

**Comment by victor-champonnois** [comment]
@huguesdk Bon c'est confirmé, l'installation écrase les données avec noupdate=True. Donc la méthode n'est pas applicable. 
Pour info, je rajoute en complément que j'ai essayé la même méthode en renommant le module (avec update_module_names en post-migration ou pre-migration) plutôt qu'en installant/désinstallant, mais ça ne fonctionne pas (j'ai des erreurs que je ne comprends pas avec "savepoint").

**Comment by victor-champonnois** [comment]
- j'ai demandé de l'aide sur sur Odoo-fr

**Comment by victor-champonnois** [comment]
conclusion from meeting with @huguesdk : we looked for a way to rename modules in easy_my_coop's pre-migration, but it raises an error after the pre-migration (during the update of easy_my_coop), probably because odoo cannot found the data to update, since they were renamed :
`odoo.exceptions.MissingError: ('One of the records you are trying to modify has already been deleted (Document type: Module).\n\n(Records: (489,), User: 1)', None)` 

We looked for some way 
- to prevent the update of easy_my_coop, but without success.
- to prevent the override of 'no-update' data during install, but also without success.

Conclusion : stick with the external script ran manually.

**Comment by victor-champonnois** [comment]
Followup after Sylvain Le Gal's answer. The following method works and preserves the data (tested by modifying mail template data). I copy his answer :

> Etape 1 : (ancien module) : module_1 est installé en version 12.0.1 avec toutes les datas et tout ce qui va bien.
> Etape 2 : (refactoring)
>     module_1 dépend de module_2.
>     module_1 est vide (plus de data, plus de python, plus rien.) Tout est dans module 2.
>     dans le module_2, en pre-init, appelez des scripts qui rename les xml_ids de module_1.* en module_2.*.
> 
> Etape 3 (switch) : 
>     Faire un update all qui va installer le module 2 par dépendance.
> 
> Etape 4 : (état final)
>     désinstaller module_1, qui est une coquille vide.

See the PR https://github.com/coopiteasy/vertical-cooperative/pull/326 for the code

Le gros bonus c'est qu'on peut utiliser cette méthode pour splitter les modules : on ajoute plusieurs dépendances dans l'ancien module et on renomme les xml_id au cas par cas.

Note : I found an example of this technique in an OCA repo here : https://github.com/OCA/sale-workflow/tree/12.0/sale_restricted_qty

**Comment by victor-champonnois** [comment]
discussion with Pol:
- we don't have time to do this for vertical cooperative, because it should be deployed mid-June (so deployed in test soon)
- this method will be great for refactoring obeesdoo

**Comment by robinkeunen** [comment]
Moved to https://github.com/orgs/beescoop/projects/2/views/2
