### ISSUE TITLE
Refactor recaptcha code out of `cooperator_website` into module `cooperator_portal_recaptcha`.

### ISSUE THREAD

**Issue by carmenbianca** [coopiteasy/vertical-cooperative#283]
Raised in #231 

edited to reflect reality after @victor-champonnois ' comment:

cooperator_website depends on `portal_recaptcha` (formerly `website_recaptcha_reloaded` or `website_recaptcha`), which is not in the OCA.

Possible solutions:

1. Move `portal_recaptcha` into this repository as `cooperator_portal_recaptcha`, then later maybe consider moving it to a different OCA repo as `website_recaptcha`.
2. Directly submit `portal_recaptcha` to the OCA so that we can depend on it.
3. Refactor `cooperator_website` to use `website_form_recaptcha` (OCA module). `cooperator_website` does not presently use `website_form`.
4. Refactor recaptcha code out of `cooperator_website`. Create a non-OCA module `cooperator_portal_recaptcha` that adds the functionality back in, with a dependency on the non-OCA module `portal_recaptcha`. Then later consider moving these modules to the OCA.

**Comment by victor-champonnois** [comment]
Note : actually it's going to be called "portal_recaptcha", since it does not depend on `website` anymore, but on `portal`.

**Comment by carmenbianca** [comment]
Link to description of situation: https://github.com/coopiteasy/vertical-cooperative/issues/214#issuecomment-1098270958

**Comment by carmenbianca** [comment]
I take this.

**Comment by victor-champonnois** [comment]
> I take this.

Noted, I think you should start working on top of this branch : https://github.com/coopiteasy/vertical-cooperative/pull/292

**Comment by victor-champonnois** [comment]
@carmenbianca (and @robinkeunen FYI)
>Whatever the case, cooperator_website presently has some recaptcha logic that depends on portal_recaptcha. We said to put that logic in cooperator_portal_recaptcha instead, but shouldn't that be cooperator_website_recaptcha? And why are we depending on portal_recaptcha instead of website_recaptcha in that case?

My understanding of the option 4 that we chose:
AS IS:
-  `cooperator_website` containing the form with the captcha, depending on `portal_recaptcha`
-  `portal_recaptcha` : a generic module that allow to insert recaptcha in any page that depends on portal (and by extension on website). 

TO BE:
- `cooperator_website` containing only the form
- `portal_recaptcha` (stays the same)
- `cooperator_portal_recaptcha` that extend cooperator_website to include the recaptcha, using `portal_recaptcha`. It could also be `cooperator_website_recaptcha`, which would make more sense, I agree.

Note: in this configuration, the refactoring of website_recaptcha to portal_recaptcha was not useful in the short run, since we depends on website because of cooperator_website. But portal_recaptcha could still be proposed to the OCA.
I think also that in the future we could tend towards a split between "portal modules" that could be extended by "website modules", this is a first step towards that goal.

(final version after messin up and editing a dozen times ^^)

**Comment by robinkeunen** [comment]
👍
