### ISSUE TITLE
As an existing user, I can't subscribe to a share in the online form

### ISSUE THREAD

**Issue by robinkeunen** [coopiteasy/vertical-cooperative#295]
- odoo finds an existing user
- click on "do you have an account" and login

=> some (required) fields are not filled
<img width="871" alt="Screenshot 2022-04-02 at 19 13 55" src="https://user-images.githubusercontent.com/3082119/161393851-93e26e8c-f7c6-4119-84c5-2e8195eecd5c.png">

**Comment by victor-champonnois** [comment]
Assignin myself since it's related to the form

**Comment by vdewulf** [comment]
@victor-champonnois I tested again because someone wrote on our test document that he was unable to reproduce.
Here is the video:
https://drive.google.com/file/d/12K9jTA2fZthW1wWhX_VWiztyjGdx86ob/view?usp=sharing
I tested on oufticoop.komunigi.test.coopiteasy.be but then also on https://oufticoop.test.coopiteasy.be/
I understand that this issue is not related to the renaming, but related to the update of the form (I suppose).
@polchampion did you test the scenario of someone with an account and taking new shares with the new form?

The button "Do you already have an account" which is still there after login can stay there, it's really minor.
The real issue to deal with is that someone cannot take new shares with the new form (and I fear it's the case also on production databases).

So this should be high priority if I'm right (but I might be wrong)

**Comment by victor-champonnois** [comment]
@vdewulf @polchampion 
Thank you for the video virginie :)
Actually the issue is not related to the update of the form, but to the renaming, since the error does not happen on non-komunigi test databases (see https://oufticoop.test.coopiteasy.be/become_cooperator for instance). So it is not high priority I believe, since it is not a bug in prod.

I'll look into it !

**Comment by vdewulf** [comment]
@victor-champonnois I was able to reproduce the same issue on https://oufticoop.test.coopiteasy.be/become_cooperator 
I don't know if my message was clear enough. So it's not related to the renaming.

**Comment by victor-champonnois** [comment]
@vdewulf OK sorry I see the bug now.

It only happens after validating the form once. If you click on "Do you already have an account" while in the `https://oufticoop.test.coopiteasy.be/page/become_cooperator` page it's OK. But after a first validation it goes to the https://oufticoop.test.coopiteasy.be/page/suscribe_share url. Then clicking on "Already have an account" redirect to https://oufticoop.test.coopiteasy.be/web/login?redirect=http://oufticoop.test.coopiteasy.be/subscription/subscribe_share while it should be redirecting to https://oufticoop.test.coopiteasy.be/web/login?redirect=http://oufticoop.test.coopiteasy.be/become_cooperator

Note : I think this issue was also present in the previous version of the form.

- The quick fix is to change the redirection URL from the "do you already have an account" from `"/web/login?redirect=#{ request.httprequest.url }"` to  `/web/login?redirect=become_cooperator_page` (I need to search how to do that)
- The deep fix is to refactor the controller to avoid having the structure with two routes: "become_cooperator" and "suscription/suscribe_share". I think this one is too long to do it now.

FYI @robinkeunen and @remytms

**Comment by victor-champonnois** [comment]
@vdewulf it's deployed in test (in 12-test DBs, not komunigis DB) oufticoop.test.coopiteasy.be for instance
